-d /home/tallguydesi/Documents/GitHub/DSP_Hi_Res_Audio_DAC/impl/gwsynthesis/DSP_DAC_UDA1334.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/tallguydesi/Documents/GitHub/DSP_Hi_Res_Audio_DAC/src/DSP_DAC_UDA1334.cst
-cfg /home/tallguydesi/Documents/GitHub/DSP_Hi_Res_Audio_DAC/impl/pnr/device.cfg
-sdc /home/tallguydesi/Documents/GitHub/DSP_Hi_Res_Audio_DAC/src/DSP_DAC_UDA1334.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
